import type { Metadata } from "next";
import "./globals.css";
import { TopBar } from "@/components/topbar";
import { Filters } from "@/components/filters";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={"antialiased"}>
        <main className="w-screen h-screen flex flex-row justify-center items-center">
          <div className="grid grid-cols-12 grid-rows-12 gap-8 h-180 w-300 bg-gray-100 rounded-2xl bg-neutral-700 p-8">
            <section className="col-span-12 row-span-1">
              <TopBar />
            </section>
            <section className="col-span-3 row-span-11">
              <Filters />
            </section>
            <section className="col-span-9 row-span-11">{children}</section>
          </div>
        </main>
      </body>
    </html>
  );
}
