import type { Metadata } from "next";
import "./globals.css";
import { TopBar } from "@/components/topbar";
import { Filters } from "@/components/filters";
import { MSWLoader } from "@/mocks/msw-loader";

export const metadata: Metadata = {
  title: "E-commerce App",
  description: "Generated by JK",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <MSWLoader />
      <body className={"h-screen p-8 antialiased box-border"}>
        <div className="flex flex-col h-full">
          <div className="flex-1 overflow-hidden rounded-xl">
            <div className="grid grid-cols-12 grid-rows-12 bg-zinc-800 h-full py-4 px-8">
              <section className="col-span-12 row-span-1">
                <TopBar />
              </section>
              <aside className="col-span-3 row-span-11 overflow-y-auto custom-scrollbar pr-2">
                <Filters />
              </aside>
              <main className="col-span-9 row-span-11 overflow-y-auto custom-scrollbar px-2">
                {children}
              </main>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
